In [19]:
import pandas as pd
import numpy as np

In [1]:
import pandas as pd
import numpy as np
import fitz
from sentence_transformers import SentenceTransformer
import faiss

/Users/shrinivasdachawar/Downloads/My_docccc/zzti/strategies/rag_envsource/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [20]:
df_ann=pd.read_parquet("/Users/shrinivasdachawar/Downloads/My_docccc/zzti/strategies/data/Announcements/announcements.parquet")

In [21]:
df_ann1=df_ann[df_ann['date']>'2026-04-01 18:40:24']

In [22]:
df_ann1.tail()

,symbol,seq_id,subject,company_name,attachment_text,industry,has_xbrl,date_raw,announcement_datetime,sort_datetime,attachment_url,date,index_name
163494,ASIANTILES,106596857,shareholders meeting,Asian Granito India Limited,Asian Granito India Limited has informed the E...,Ceramics And Sanitaryware,True,22042026150746,22-Apr-2026 15:07:46,2026-04-22 15:07:46,https://nsearchives.nseindia.com/corporate/ASI...,2026-04-22 15:07:46,equities
163495,LYPSAGEMS,106596861,general updates,Lypsa Gems & Jewellery Limited,Lypsa Gems & Jewellery Limited has informed th...,None,True,22042026151241,22-Apr-2026 15:12:41,2026-04-22 15:12:41,https://nsearchives.nseindia.com/corporate/LYP...,2026-04-22 15:12:41,equities
163496,HNDFDS,106596862,record date,Hindustan Foods Limited,Hindustan Foods Limited has informed the Excha...,None,True,22042026151311,22-Apr-2026 15:13:11,2026-04-22 15:13:11,https://nsearchives.nseindia.com/corporate/913...,2026-04-22 15:13:11,equities
163497,SENCO,106596863,copy of newspaper publication,Senco Gold Limited,Senco Gold Limited has informed the Exchange a...,None,True,22042026151351,22-Apr-2026 15:13:51,2026-04-22 15:13:51,https://nsearchives.nseindia.com/corporate/Sen...,2026-04-22 15:13:51,equities
163498,AGI,106596864,general updates,AGI Greenpac Limited,AGI Greenpac Limited has informed the Exchange...,None,True,22042026151533,22-Apr-2026 15:15:33,2026-04-22 15:15:33,https://nsearchives.nseindia.com/corporate/HSI...,2026-04-22 15:15:33,equities

In [23]:
df_tr=pd.DataFrame(df_ann1[(df_ann1['subject']=='analysts/institutional investor meet/con. call updates')]['attachment_text'].value_counts()).reset_index()

In [24]:
print(df_tr.columns)

Index(['attachment_text', 'count'], dtype='str')

In [25]:
results=df_tr[df_tr['attachment_text'].str.lower().str.contains("link", na=False)]

In [26]:
# 1. Filter by subject and "link" in attachment_text
mask = (df_ann1['subject'] == 'analysts/institutional investor meet/con. call updates') & \
       ((df_ann1['attachment_text'].str.lower().str.contains("link", na=False)) | df_ann1['attachment_text'].isnull())

# 2. Apply mask, sort by date (descending), and take top 200
df_tr1 = df_ann1[mask].sort_values(by='date', ascending=False)

In [27]:
df_share=df_ann[df_ann['subject'].str.lower().str.contains("analysts/institutional investor meet/con. call updates")].sort_values('date', ascending=False).head(50)

In [29]:
df_bulk=pd.read_parquet("/Users/shrinivasdachawar/Downloads/My_docccc/zzti/strategies/data/deals_data/bulk_deals.parquet")

In [32]:
df_bulk.head()

,Date,Symbol,Security Name,Client Name,Buy / Sell,Quantity Traded,Trade Price / Wght. Avg. Price,Remarks,Buy/Sell,fetch_date
0,2025-09-29,AAATECH,AAA Technologies Limited,CRAFT EMERGING MARKET FUND PCC- CITADEL CAPITA...,BUY,400000,78.60,-,None,None
1,2025-09-29,AAATECH,AAA Technologies Limited,RUCHI ANJAY AGARWAL,SELL,400000,78.60,-,None,None
2,2025-09-29,AETHER,Aether Industries Limited,AMANSA HOLDINGS PRIVATE LIMITED,BUY,1282613,735.00,-,None,None
3,2025-09-29,AETHER,Aether Industries Limited,GOLDMAN SACHS FDS GOLDMAN SACHS INDIA EQ PORTF...,SELL,1151084,735.01,-,None,None
4,2025-09-29,ANZEN,Anzen Ind Ene Yld Plu Tru,GO DIGIT GENERAL INSURANCE LIMITED,BUY,2175000,115.00,-,None,None

In [9]:
df_orders=pd.read_parquet("/Users/shrinivasdachawar/Downloads/My_docccc/zzti/strategies/data/Announcements/orders_100.parquet")

In [47]:
df_orders.columns

Index(['symbol', 'subject', 'company_name', 'date_raw',
       'announcement_datetime', 'sort_datetime', 'attachment_url', 'date',
       'date_only', 'pdf_text'],
      dtype='str')

In [119]:
import re

def smart_chunk_text(text, chunk_size=400, overlap=100):
    sentences = re.split(r'(?<=[.!?]) +', text)
    
    chunks = []
    current_chunk = ""
    
    for sentence in sentences:
        if len(current_chunk) + len(sentence) < chunk_size:
            current_chunk += " " + sentence
        else:
            chunks.append(current_chunk.strip())
            current_chunk = sentence
    
    if current_chunk:
        chunks.append(current_chunk.strip())
    
    return chunks

In [120]:
all_chunks = []

for _, row in df_orders.iterrows():
    chunks = smart_chunk_text(row["pdf_text"])
    
    for chunk in chunks:
        all_chunks.append({
            "text": chunk,
            "symbol": row["symbol"],
            "date": row["date"],
            "source": "announcement"
        })

In [121]:
chunks_df = pd.DataFrame(all_chunks)

In [122]:
all_chunks

[{'text': '',
  'symbol': 'ADANIPOWER',
  'date': Timestamp('2026-04-02 19:44:15'),
  'source': 'announcement'},
 {'text': 'date: april 2, 2026\nbse limited national stock exchange of india limited\nfloor 25, p j towers, exchange plaza,\ndalal street, bandra kurla complex,\nmumbai – 400 001 bandra (e), mumbai – 400 051\nscrip code: 533096 scrip code: adanipower\ndear sir,\nsub: intimation under regulation 30 of the sebi (listing obligations and disclosures\nrequirements) regulations, 2015 – letter of award\nadani power limited has received a letter of award (“loa”) from maharashtra state\nelectricity distribution co.',
  'symbol': 'ADANIPOWER',
  'date': Timestamp('2026-04-02 19:44:15'),
  'source': 'announcement'},
 {'text': 'limited (“msedcl”) for supply of 2500 mw re rtc power\nfor a period of 25 years from scheduled commencement date of supply, upon apl\nbeing declared as the successful bidder in the e-ra results.\nthe details, as required under sebi (listing obligations and disclosure requirements)\nregulations, 2015 read with sebi master circular bearing reference number\nho/49/14/14(7)2025-cfd-pod2/i/3762/2026 dated january 30, 2026, is attached\nherewith as annexure a.\nloa has been received by the company at 8:30 pm on april 1, 2026.\nyou are requested to take the same on your record.\nthanking you\nyours faithfully,\nfor, adani power limited\npuneet bansal\ncompany secretary\nadani power limited tel +91 79 2656 7555\n“adani corporate house” fax +91 79 2555 7177\nshantigram, near vaishno devi circle, info@adani.com\ns.',
  'symbol': 'ADANIPOWER',
  'date': Timestamp('2026-04-02 19:44:15'),
  'source': 'announcement'},
 {'text': 'g. highway, khodiyar, www.adanipower.com\nahmedabad-382421, gujarat india\ncin: l40100gj1996plc030533\nregistered office: “adani corporate house”, shantigram, near vaishno devi circle, s. g. highway, khodiyar, ahmedabad-382421annexure a\nsr. particulars details\nno.\n1. name of the entity awarding the maharashtra state electricity\norder(s)/contract(s) distribution company limited\n(“msedcl”).\n2.',
  'symbol': 'ADANIPOWER',
  'date': Timestamp('2026-04-02 19:44:15'),
  'source': 'announcement'},
 {'text': 'significant terms and conditions of as per the provisions of the tender\norder(s)/contract(s) awarded, in floated by msedcl and subject to the\nbrief conditions stated in the instant loa.\n3. whether order(s)/contract(s) have domestic entity\nbeen awarded by\ndomestic/international entity\n4. nature of order(s)/contract(s) long term supply of re rtc power.\n5.',
  'symbol': 'ADANIPOWER',
  'date': Timestamp('2026-04-02 19:44:15'),
  'source': 'announcement'},
 {'text': 'whether domestic or international domestic\n6. time period by which the the power supply under the power\norder(s)/contract(s) is to be supply agreement will be for a period of\nexecuted 25 years from scheduled\ncommencement date of supply (ssd).\n7. broad consideration or size of the the contract award is for supply of re\norder(s)/contract(s) rtc power of 2500 mw.\n8.',
  'symbol': 'ADANIPOWER',
  'date': Timestamp('2026-04-02 19:44:15'),
  'source': 'announcement'},
 {'text': 'whether the promoter/ promoter no\ngroup / group companies have any\ninterest in the entity that awarded\nthe order(s) / contract(s)? if yes,\nnature of interest and details\nthereof.\n9. whether the order(s)/contract(s) no\nwould fall within related party\ntransactions?',
  'symbol': 'ADANIPOWER',
  'date': Timestamp('2026-04-02 19:44:15'),
  'source': 'announcement'},
 {'text': 'if yes, whether the\nsame is done at “arm’s length”\nadani power limited tel +91 79 2656 7555\n“adani corporate house” fax +91 79 2555 7177\nshantigram, near vaishno devi circle, info@adani.com\ns. g. highway, khodiyar, www.adanipower.com\nahmedabad-382421, gujarat india\ncin: l40100gj1996plc030533\nregistered office: “adani corporate house”, shantigram, near vaishno devi circle, s. g.',
  'symbol': 'ADANIPOWER',
  'date': Timestamp('2026-04-02 19:44:15'),
  'source': 'announcement'},
 {'text': 'highway, khodiyar, ahmedabad-382421',
  'symbol': 'ADANIPOWER',
  'date': Timestamp('2026-04-02 19:44:15'),
  'source': 'announcement'},
 {'text': 'rvnl/secy/stex/2026-27 02.04.2026\nnational stock exchange of india ltd. bse ltd.\nexchange plaza, department of corporate service,\nplot no.',
  'symbol': 'RVNL',
  'date': Timestamp('2026-04-02 18:27:27'),
  'source': 'announcement'},
 {'text': 'c/1, g block, phiroze jeejeebhoy towers,\nbandra-kurla complex, dalal street,\nbandra (e), mumbai - 400051 mumbai- 400001\nsymbol: rvnl scrip: 542649\nsub: disclosure under regulation 30 of sebi (lodr) regulations, 2015- receipt of loa\nfrom south central railway\ndear sir/madam,\npursuant to regulation 30 of sebi (listing obligations and disclosure requirements) regulations,\n2015, it is hereby informed that rail vikas nigam limited has received loa from south central\nrailway for "design, supply, erection, testing and commissioning for ohe upgradation of existing\n1x25kv system to 2x25kv at feeding system with feeder and earthing works in ongole (ogl)\n(incl) - gudur (gdr) (incl) section of vijayawada division under south central railway, total 154\nrkm/ 462 tkm.”\nthe aforesaid work is in the normal course of business of the company.\ndeclaration as per sebi master circular no.',
  'symbol': 'RVNL',
  'date': Timestamp('2026-04-02 18:27:27'),
  'source': 'announcement'},
 {'text': 'ho/49/14/14(7)2025-cfd-pod2/i/3762/2026 dated\n30th january, 2026 is enclosed as annexure a.\nkindly take the same on record.\nthanking you,\nyours faithfully,\nfor rail vikas nigam limited\n(kalpana dubey)\ncompany secretary & compliance officer\nregd.',
  'symbol': 'RVNL',
  'date': Timestamp('2026-04-02 18:27:27'),
  'source': 'announcement'},
 {'text': 'office: world trade center, tower a, 6th to 9th floor, nauroji nagar, new delhi- 110029\nphone: +91-11-26738299, fax: +91-11-26182957, e-mail: info@rvnl.org, web: www.rvnl.organnexure-a\ns. particulars details of projects\nno.\na. name of the entity awarding the south central railway\norder(s)/contract(s);\nb.',
  'symbol': 'RVNL',
  'date': Timestamp('2026-04-02 18:27:27'),
  'source': 'announcement'},
 {'text': 'significant terms and conditions of general contract conditions\norder( s )/contract( s) awarded in\nbrief·\nc. whether order(s) / contract(s) have domestic entity\nbeen awarded by domestic/\ninternational entity;\nd.',
  'symbol': 'RVNL',
  'date': Timestamp('2026-04-02 18:27:27'),
  'source': 'announcement'},
 {'text': 'nature of order(s) / contract(s); design, supply, erection, testing and\ncommissioning for ohe upgradation of\nexisting 1x25kv system to 2x25kv at\nfeeding system with feeder and earthing\nworks in ongole (ogl) (incl) - gudur (gdr)\n(incl) section of vijayawada division under\nsouth central railway,total 154 rkm/ 462\ntkm. tender no: 2x25kv-ohe-ogl-gdr-15\ne. whether domestic or international; domestic\nf.',
  'symbol': 'RVNL',
  'date': Timestamp('2026-04-02 18:27:27'),
  'source': 'announcement'},
 {'text': 'time period by which the 24 months\norder( s )/contract(s ) is to be\nexecuted;\ng. broad consideration or size of the cost of work is rs 242,49,86,547.22/- (rs\norder(s)/contract(s); two hundred forty-two crore forty-nine\nlakh eighty-six thousand five hundred\nforty-seven rupees and twenty-two paisa)\nincluding applicable taxes\nh.',
  'symbol': 'RVNL',
  'date': Timestamp('2026-04-02 18:27:27'),
  'source': 'announcement'},
 {'text': 'whether the promoter/ promoter no\ngroup / group companies have any\ninterest in the entity that awarded\nthe order( s )/contract(s )? if yes,\nnature of interest and details\nthereof;\ni. whether the order( s )/contract( s) no\nwould fall within related party\ntransactions?',
  'symbol': 'RVNL',
  'date': Timestamp('2026-04-02 18:27:27'),
  'source': 'announcement'},
 {'text': 'if yes, whether the\nsame is done at "arm\'s lemrth".\nsanjib digitally signed\nby sanjib\nkumar kumar mishra\ndate: 2026.04.02\nmishra\n17:33:34 +05\'30\'\npage 2 of 2',
  'symbol': 'RVNL',
  'date': Timestamp('2026-04-02 18:27:27'),
  'source': 'announcement'},
 {'text': 'april 2, 2026\nbse limited national stock exchange of india limited\nsir phiroze jeejeebhoy towers exchange plaza, 5th floor,\ndalal street, fort, plot no.',
  'symbol': '3IINFOLTD',
  'date': Timestamp('2026-04-02 17:40:29'),
  'source': 'announcement'},
 {'text': 'c-1, block g\nmumbai – 400 001 bandra kurla complex,\nsecurity code: 532628 mumbai – 400 051\nscrip code: 3iinfoltd\ndear sir/madam,\nsub: intimation under regulation 30 of the sebi (listing obligations and disclosure\nrequirements) regulations, 2015 – award of order\npursuant to regulation 30 of the sebi (listing obligations and disclosure requirements)\nregulations, 2015, we hereby inform you that 3i infotech inc., usa, a material wholly owned\nstep-down subsidiary of the company has received an order on april 1, 2026 from a leading\nmedical supplies delivery services company, for modernization and re-engineering of its\nplatforms.\nthe engagement involves end-to-end transformation of the client’s applications into a\nscalable, cloud-native digital commerce ecosystem, integrated with erp through a secure\nmiddleware layer.',
  'symbol': '3IINFOLTD',
  'date': Timestamp('2026-04-02 17:40:29'),
  'source': 'announcement'},
 {'text': 'the solution includes microservices-based architecture, ai-enabled\nsearch and chatbot capabilities, middleware-driven system integration, and database\nmodernization, aimed at enhancing user experience, operational efficiency, and real-time\nbusiness visibility.',
  'symbol': '3IINFOLTD',
  'date': Timestamp('2026-04-02 17:40:29'),
  'source': 'announcement'},
 {'text': 'the total value of the order is approximately ₹1.63 crores.\nthe requisite details as per sebi master circular ho/49/14/14(7)2025-cfd-pod2/i/3762/2026\ndated january 30, 2026, are enclosed as annexure.\nthe above information will also be made available on the website of the company.\nthe company is making this disclosure on a voluntary basis as amount involved is below the\nmateriality threshold limits as per aforementioned regulation.\nyou are requested to take you same on the record.\nthanking you.\nyours faithfully,\nfor 3i infotech limited\nvarika rastogi\ncompany secretary & compliance officer\nencl: as aboveannexure\nsr.',
  'symbol': '3IINFOLTD',
  'date': Timestamp('2026-04-02 17:40:29'),
  'source': 'announcement'},
 {'text': 'no particulars details\nname of the entity awarding the a leading medical supplies delivery services\na\norder(s)/contract(s) c ompany*\nsignificant terms and conditions of modernization and re-engineering of its\nb\norder(s)/contract(s) awarded in brief platforms\nwhether order(s)/contract(s) have been\ninternational\nc awarded by domestic/ international\nentity\nto modernize the platform into intelligent and\nscalable digital, having ai & analytics enabled,\nd nature of order(s)/contract(s)\ncommercial ecosystems, seamlessly integrated\nwith erp through secured middleware layer\ne whether domestic or international international\ntime period by which the\nf 7 months\norder(s)/contract(s) is to be executed\nbroad consideration or size of the\ng $ 1,75,000\norder(s)/contract(s)\nwhether promoter/promoter\nna\ngroup/group companies have any\nh\ninterest in the entity that awarded the\norder(s)/contract(s)\nwhether the order(s)/contract(s) would no\ni\nfall within related party transactions\n*due to confidentiality obligations, the name of the customer cannot be disclosed',
  'symbol': '3IINFOLTD',
  'date': Timestamp('2026-04-02 17:40:29'),
  'source': 'announcement'},
 {'text': '2nd april, 2026\nnational stock exchange of india ltd. bse limited\nexchange plaza, c-1, block g, p. j.',
  'symbol': 'TEXRAIL',
  'date': Timestamp('2026-04-02 16:55:40'),
  'source': 'announcement'},
 {'text': 'towers,\nbandra kurla complex dalal street,\nbandra (e), mumbai – 400051 mumbai – 400001\nsymbol – texrail scrip code – 533326\nsubject: receipt of order - disclosure under regulation 30 of sebi (listing obligations and\ndisclosure requirements), regulations 2015\ndear sirs,\npursuant to regulation 30, we wish to inform you that west central railway has awarded an order\nof rs.',
  'symbol': 'TEXRAIL',
  'date': Timestamp('2026-04-02 16:55:40'),
  'source': 'announcement'},
 {'text': '0.93 crore as a developmental order for 38 nos. bogie frame for icf design coaches.\nthe details as required under the sebi (listing obligations and disclosure requirements)\nregulations, 2015 read with sebi circular no. ho/49/14/14(7)2025-cfd-pod2/i/3762/2026 dated\n30th january, 2026 are provided hereunder:\nsl. no particulars details\n1.',
  'symbol': 'TEXRAIL',
  'date': Timestamp('2026-04-02 16:55:40'),
  'source': 'announcement'},
 {'text': 'name of the entity awarding the west central railway\norder(s)/contract(s)\n2. significant terms and conditions of developmental order for 38 nos. bogie\norder(s)/contract(s) awarded in brief frame for icf design coaches.\n3. whether order(s) / contract(s) have domestic\nbeen awarded by domestic/\ninternational entity\n4. nature of order(s) / contract(s) developmental order for 38 nos.',
  'symbol': 'TEXRAIL',
  'date': Timestamp('2026-04-02 16:55:40'),
  'source': 'announcement'},
 {'text': 'bogie\nframe for icf design coaches.\n5. whether domestic or international domestic\n6. time period by which the order(s) / within 90 days from the date of purchase\ncontract(s) is to be executed order.\n7. broad consideration or size of the rs. 0.93 crores (excluding taxes)\norder(s)/contract(s)8.',
  'symbol': 'TEXRAIL',
  'date': Timestamp('2026-04-02 16:55:40'),
  'source': 'announcement'},
 {'text': 'whether the promoter/ promoter no\ngroup / group companies have any\ninterest in the entity that awarded the\norder(s)/ contract(s)? if yes, nature of\ninterest and details thereof\n9. whether the order(s)/contract(s) no\nwould fall within related party\ntransactions?',
  'symbol': 'TEXRAIL',
  'date': Timestamp('2026-04-02 16:55:40'),
  'source': 'announcement'},
 {'text': 'if yes, whether the same\nis done at “arm’s length”\nthis is for your information and record.\nyours faithfully,\nfor texmaco rail & engineering limited\nsandeep kumar sultania\ncompany secretary &\ncompliance officer',
  'symbol': 'TEXRAIL',
  'date': Timestamp('2026-04-02 16:55:40'),
  'source': 'announcement'},
 {'text': '',
  'symbol': 'CEIGALL',
  'date': Timestamp('2026-04-02 13:02:17'),
  'source': 'announcement'},
 {'text': 'date: 02.04.2026\nto, to,\nthe general manager, manager-listing compliance,\ndepartment of corporate national stock exchange of india\nservices, bse limited limited, exchange plaza, c-1, block\nphiroze jeejeebhoy towers g, bandra kurla complex, bandra\ndalal street, mumbai- east, mumbai – 400 051\n400 001 symbol: ceigall\nscrip code:544223 isin: ineoag901020\nisin: ineoag901020\nsubject: intimation for execution of power purchase agreements (ppas).\ndear sir/madam,\nin continuation of our letter dated january 2, 2026 and pursuant to regulation 30 of sebi (listing\nobligations and disclosure requirements) regulation, 2015, we wish to inform that ceigall green\nenergy mp limited, wholly owned subsidiary of ceigall india limited has completed the execution\nof 15 power purchase agreements (ppas) on 1st april, 2026, with madhya pradesh power management\ncompany limited (mppmcl) for the awarded capacity of 130 mw under surya mitra krishi feeder\nyojna.\nthe details required under regulation 30 of sebi (lodr) regulations, 2015 read with sebi circular\nno.',
  'symbol': 'CEIGALL',
  'date': Timestamp('2026-04-02 13:02:17'),
  'source': 'announcement'},
 {'text': 'ho/49/14/14(7)2025-cfd-pod2/i/3762/2026 dated january 30, 2026 are as under: -\nsl. particulars remarks\nno.\n1. name of the entity awarding the madhya pradesh power management company limited\norder(s) /contract(s); (mppmcl)\n2. significant terms and conditions 1.',
  'symbol': 'CEIGALL',
  'date': Timestamp('2026-04-02 13:02:17'),
  'source': 'announcement'},
 {'text': 'power purchase agreement entered for solar\nof order(s) / contract(s) awarded photovoltaic power generating stations for awarded\nin brief; capacity of 130 mw .\n2. implement, operate, maintain and supply power for\n25 years under long term ppa at quoted tariff of rs.\n2.85 per unit.\nunder surya mitra krishi feeder yojana.\n3.',
  'symbol': 'CEIGALL',
  'date': Timestamp('2026-04-02 13:02:17'),
  'source': 'announcement'},
 {'text': 'whether order(s) / contract(s)\nhave been awarded by domestic / domestic\ninternational entity;\n4. nature of order(s) / contract(s); power purchase agreements (ppas) executed between\nceigall green energy mp limited and madhya pradesh\npower management company limited (mppmcl).\n5. whether domestic or domestic\ninternational.6.',
  'symbol': 'CEIGALL',
  'date': Timestamp('2026-04-02 13:02:17'),
  'source': 'announcement'},
 {'text': 'time period by which the • 12 months of work execution\norder(s) / contract(s) is to be • 25 years of operational period\nexecuted.\n7 broad consideration or size of the epc cost approx. ₹572.00 crore (including gst)\norder(s) / contract(s);\n8. whether the promoter/ promoter\ngroup / group companies have\nany interest in the entity that\nawarded the order(s)/contract(s)?',
  'symbol': 'CEIGALL',
  'date': Timestamp('2026-04-02 13:02:17'),
  'source': 'announcement'},
 {'text': 'no\nif yes, nature of interest and\ndetails thereof.\n9. whether the order(s)/ contract(s)\nwould fall within related party\ntransactions?',
  'symbol': 'CEIGALL',
  'date': Timestamp('2026-04-02 13:02:17'),
  'source': 'announcement'},
 {'text': 'if yes, whether the no\nsame is done at “arm’s length”.\npress release titled “ceigall executes 15 ppas with mppmcl for 130 mw solar capacity” is also\nenclosed as annexure-1.\nthe same is also available on the website of the company at www.ceigall.com\nyou are requested to take the above information on your record.\nthanking you,\nyours faithfully,\nfor ceigall india limited\nmegha kainth\ncompany secretary\nmembership no: f7639\nencl.: as aboveannexure-1\nceigall executes 15 ppas with mppmcl for 130 mw solar capacity\nnew delhi, april 02, 2026: ceigall green energy mp limited, a wholly owned subsidiary of ceigall\nindia limited (‘cil’), has completed the execution of 15 power purchase agreements (ppas)\nwith madhya pradesh power management company limited (mppmcl) for the total awarded\nsolar capacity of 130 mw under the surya mitra krishi feeder yojana.\nas per the agreement, ceigall green energy mp limited will implement, operate, maintain, and\nsupply power from solar photovoltaic generating stations for a period of 25 years at a quoted tariff\nof rs 2.85 per unit.',
  'symbol': 'CEIGALL',
  'date': Timestamp('2026-04-02 13:02:17'),
  'source': 'announcement'},
 {'text': 'the surya mitra krishi feeder yojana is a key government initiative aimed at\nproviding reliable daytime power to the agricultural sector through dedicated solar feeders, while\nadvancing india’s clean energy goals.',
  'symbol': 'CEIGALL',
  'date': Timestamp('2026-04-02 13:02:17'),
  'source': 'announcement'},
 {'text': 'the project carries an estimated epc cost of ₹572 crore\n(including gst) and includes a 12-month execution period, followed by a 25-year operational\nterm.\ncommenting on this milestone, ramneek sehgal, chairman & managing director, ceigall\nindia limited, said: “completing the execution of all 15 ppas marks a significant step in\nstrengthening ceigall’s presence in india’s renewable energy sector.',
  'symbol': 'CEIGALL',
  'date': Timestamp('2026-04-02 13:02:17'),
  'source': 'announcement'},
 {'text': 'the surya mitra krishi feeder\nyojana is a major initiative supporting clean and reliable energy, and we are pleased to contribute\nto its implementation.',
  'symbol': 'CEIGALL',
  'date': Timestamp('2026-04-02 13:02:17'),
  'source': 'announcement'},

In [123]:

(chunks_df.tail())

,text,symbol,date,source
774,kodanda rami reddy\ncompany secretary & compli...,LOKESHMACH,2026-03-17 19:25:33,announcement
775,sebi/ho/cfd/cfd-pod-1/p/cir/2023/123 dated: ju...,LOKESHMACH,2026-03-17 19:25:33,announcement
776,whether order(s) / contract(s) have been domes...,LOKESHMACH,2026-03-17 19:25:33,announcement
777,"9,50,01,741/-\nthe order(s)/contract(s); (incl...",LOKESHMACH,2026-03-17 19:25:33,announcement
778,"if yes,\nwhether the same is done at ""arm's le...",LOKESHMACH,2026-03-17 19:25:33,announcement

In [124]:
chunks_df[chunks_df['symbol']=='POWERMECH']

,text,symbol,date,source
94,"date: april 1, 2026\nto to\nlisting department...",POWERMECH,2026-04-01 10:38:37,announcement
95,services\nnational stock exchange of india lim...,POWERMECH,2026-04-01 10:38:37,announcement
96,the details\nof the order as required under th...,POWERMECH,2026-04-01 10:38:37,announcement
97,no particulars details\na name of the entity a...,POWERMECH,2026-04-01 10:38:37,announcement
98,"if no\nyes, whether the same is done at “arm’s...",POWERMECH,2026-04-01 10:38:37,announcement

In [125]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6614.30it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [126]:
texts = chunks_df["text"].tolist()

embeddings = model.encode(
    texts,
    show_progress_bar=True,
    batch_size=32
)

Batches:   0%|          | 0/25 [00:00<?, ?it/s]

Batches: 100%|██████████| 25/25 [00:05<00:00,  4.89it/s]

In [127]:
print(len(embeddings))
print(embeddings[0].shape)

779
(384,)

In [128]:
import faiss
import numpy as np

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)
index.add(np.array(embeddings))

In [129]:
print(index.ntotal)

779

In [130]:
def retrieve(query, k=5):
    q_emb = model.encode([query])
    
    distances, indices = index.search(q_emb, k)
    
    results = chunks_df.iloc[indices[0]]
    
    return results

In [131]:
output=retrieve("order received by adani power")

In [132]:
output

,text,symbol,date,source
3,"g. highway, khodiyar, www.adanipower.com\nahme...",ADANIPOWER,2026-04-02 19:44:15,announcement
1,"date: april 2, 2026\nbse limited national stoc...",ADANIPOWER,2026-04-02 19:44:15,announcement
2,limited (“msedcl”) for supply of 2500 mw re rt...,ADANIPOWER,2026-04-02 19:44:15,announcement
7,"if yes, whether the\nsame is done at “arm’s le...",ADANIPOWER,2026-04-02 19:44:15,announcement
95,services\nnational stock exchange of india lim...,POWERMECH,2026-04-01 10:38:37,announcement

In [133]:
retrieve("last week order received")

,text,symbol,date,source
622,the orders pertain to the supply of power dist...,MARINE,2026-03-24 10:21:14,announcement
653,the orders pertain to the supply of power dist...,MARINE,2026-03-23 13:42:25,announcement
157,"date: 31/03/2026\nto, to,\nnational stock exch...",INTERARCH,2026-03-31 16:06:47,announcement
511,sebi/ho/cfd/cfd-pod-1/p/cir/2023/123 dated jul...,PACEDIGITK,2026-03-26 12:53:10,announcement
350,"bandra (east), mumbai – 400 051, india.\nscrip...",AVANTEL,2026-03-28 13:04:59,announcement

In [78]:
print(df_orders[df_orders['symbol']=='POWERMECH']['pdf_text'].iloc[0])

date: april 1, 2026
to to
listing department dept. of corp. services
national stock exchange of india limited bse limited
exchange plaza, c-1, block g, phiroze jeejeebhoy towers
bandra kurla complex, dalal street
bandra (e), mumbai – 400 051 mumbai- 400001
symbol/security id: powermech security code: 539302
dear sir/madam,
sub: receipt of order
*****
we are pleased to inform you that the company has secured an order from hindustan zinc limited. the details
of the order as required under the sebi master circular no. sebi/ho/cfd/pod2/cir/p/0155 dated november
11, 2024, are given below:
s. no particulars details
a name of the entity awarding order(s)/ hindustan zinc limited
contract(s) (cin: l27204rj1966plc001208)
b significant terms and conditions of scope of work: the company is responsible for
order(s)/ contracts(s) awarded in brief comprehensive operation and maintenance of the 91.5 mw
cpp and transmission line up to the mrss, acting as an
independent contractor on behalf of hindustan zinc limited.
c whether order(s)/ contract(s) have been domestic entity
awarded by domestic/ international entity
d nature of order(s)/ contract(s) work order for operation and maintenance
e whether domestic or international domestic
f time period by which the within forty-eight (48) months
order(s)/contract(s) is to be executed
g broad consideration or size of the order(s) ₹ 109.22 crores (excluding goods & services tax)
h whether promoter/ promoter group/
group companies have any interest in the
entity that awarded the order(s)/ no
contract(s)?
i whether the order(s)/ contract(s) would
fall within related party transactions? if no
yes, whether the same is done at “arm’s
length”
kindly take the same on record and acknowledge the receipt.
for power mech projects limited
m. raghavendra prasad
company secretary and compliance officer